### ISSUE TITLE
Building a Docker image with Hercules Hyperion in it.

### ISSUE THREAD

**Issue by AllardKrings** [wrljet/hercules-helper#13] opened 2021-08-17 19:32 UTC
Hi Bill

just for the fun of teaching myself Docker I am trying to build a Docker-image with Hercules in it.

I use an UBUNTU 20.04 Docker-image to start from.

Here is the Docker-build file:

FROM ubuntu:21.04
RUN apt update && apt install \
         apt-utils \
         git \
         net-tools\
         wget \
        sudo -y
RUN useradd -ms /bin/bash ubuntu
USER ubuntu
WORKDIR /home/ubuntu
RUN cd ~
RUN git clone https://github.com/wrljet/hercules-helper.git
RUN mkdir herctest && cd herctest
RUN ~/hercules-helper/hyperion-buildall.sh --auto

Running this file with 

Docker build -t hercules .

I get the error:

hostinfo               =  
/bin/universe          = 
/usr/bin/arch -k       = 
/bin/arch              = aarch64
/usr/bin/oslevel       = 
/usr/convex/getsysinfo = 

UNAME_MACHINE = aarch64
UNAME_RELEASE = 5.11.0-1015-raspi
UNAME_SYSTEM  = Linux
UNAME_VERSION = #16-Ubuntu SMP PREEMPT Wed Jul 14 11:04:58 UTC 2021
configure: error: cannot guess build type; you must specify one[[ error: ]] configure failed!The command '/bin/sh -c ~/hercules-helper/hyperion-buildall.sh --auto' returned a non-zero code: 1

Do you have any suggestions?

It would be great fun to run Hercules in a Docker image!

Kind regards 

Allard

**Comment by wrljet** [comment] 2021-08-17 19:45
Allard,

I will figure that out and get back to you.

First question, what is your host system?

But there is a new feature (not fully tested yet) in Hercules-Helper that will generate
a script of commands needed to reproduce what it just did.  Without all the fanfare
and testing.  It will be perfect for this docker situation!

Bill

**Comment by wrljet** [comment] 2021-08-19 21:45
Allard,

I will figure that out and get back to you.

First question, what is your host system?

But there is a new feature (not fully tested yet) in Hercules-Helper that will generate
a script of commands needed to reproduce what it just did. Without all the fanfare
and testing. It will be perfect for this docker situation!

Bill

**Comment by AllardKrings** [comment] 2021-08-20 06:08
Hello Bill, 

host system is ubunti 20.04 on a raspberry PI-4 

I got Hercules working mostly (a few minor errors) by copying the herctest directory into my docker image during the build. Everything works fine except Regina and TUN interface. I’ll have to figure those out. I will keep you informed. 

The nicest way to do this is off course by using your hercules-helper during the build of the docker-image!

Kind regards Allard

**Comment by AllardKrings** [comment] 2021-08-20 09:13
made mistake: both host and docker image use ubuntu 21.04 hirsute

Kind regards!

Allard

**Comment by wrljet** [comment] 2021-08-20 12:47
I'll set that up and see what happens.

Bill

**Comment by wrljet** [comment] 2021-08-20 20:21
Allard,

I've found a couple problems.  Working on it...

Part of it affects all Pi Ubuntu.  I evidently broke that recently.

Bill

**Comment by AllardKrings** [comment] 2021-08-21 06:22
Hi Bill ,

great that you will help. If there is any testing I can do let me know.

Kind regards Allard

**Comment by wrljet** [comment] 2021-08-21 15:20
I fixed a bug in Hercules-Helper that affected all non-RPIOS on Pi.
The Pi hardware detection was busted.  The fix is in the repo now.

That bug is what caused the specific error you saw.
The reason was, we need to patch Regina's autoconf/etc things for the Pi.
Pi detection didn't work, so config.guess didn't get patched.  And never heard of the Pi.

With that fixed, then I ran into issues where `sudo` is required in a few places in
Hercules-Helper.  That wont' work during a Docker build because there's no terminal
to accept the password.   I worked around that in the Dockerfile by allowing sudo without a password.

And I added the -no-setcap option.

Hercules comes up.  But I haven't tried to IPL anything.

Try out this Dockerfile:

```
FROM ubuntu:21.04
RUN apt update
RUN apt install -y apt-utils
RUN apt install -y git net-tools wget curl sudo

# Pre-install packages so Hercules-Helper won't have to
RUN apt install -y time ncat build-essential cmake
RUN apt install -y autoconf automake flex gawk m4 libtool
RUN apt install -y libcap2-bin libbz2-dev zlib1g-dev

# Create our user
RUN useradd -ms /bin/bash ubuntu

# Add user to sudo group
RUN adduser ubuntu sudo

# Allow sudo without a password
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER ubuntu
WORKDIR /home/ubuntu

RUN cd ~
RUN git clone https://github.com/wrljet/hercules-helper.git
RUN mkdir herctest && cd herctest

RUN ~/hercules-helper/hyperion-buildall.sh --auto --no-setcap
```

**Comment by AllardKrings** [comment] 2021-08-23 12:32
Hi Bill,

I tried your Dockerfile and it works fine. I was able to 
- build the Dockerfile, 
- run it, 
- connect to it from a console at port 3270
- IPL the OS
- connect to the OS in terminal-mode

The only thing that does not work is the TUN interface. There are some issues with the TUN interface using them from within docker.

I tried: 

docker run --privileged -u 0 -it -v /share:/share --device /dev/net/tun:/dev/net/tun --network=host hercules

where 
' -privilged"  means having all the administrative rights on the host 
'-u  0'  means running as root;
'it' means running it interactively
'-v /share:/share' means mounting the volume where the OS resides 
'--device dev/net/tun:/dev/net/tun' means shareng the hosts dev/net/tun with the docker image
'--network=host' means using the hosts network

The TUN interface is opened but there  no IP-adresses configured on it.

Maybe you or another Docker-expert has any suggestions.

It might have something to do with  priviliges that the hercules program needs within the container but does not have since it is the hercules program that configures the TUN-interface.
 
Kind regards Allard

**Comment by AllardKrings** [comment] 2021-08-23 12:49
This is the error from Hercules:

HHC00901I 0:0E20 CTCI: Interface tun0, type TUN opened                                                                  
HHC00136E Error in function execlp(): No such file or directory                                                         
HHC00007I Previous message from function 'IFC_IOCtl' at tuntap.c(1118)                                                  
herc =====>

**Comment by wrljet** [comment] 2022-02-16 22:55
Allard,

Are we all happy here?  May I close this issue?

Bill

**Comment by AllardKrings** [comment] 2022-07-05 13:33
Hi Bill,

I appologize for the very late response. Yes you may close this issue! Thanks for your help!

Allard

**Closed** 2022-07-05 14:25 UTC
